inherit_from:
  - https://potpourri.hausgold.de/config/rubocop.yml
  - https://potpourri.hausgold.de/config/rubocop-gem.yml

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-rspec
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.2
  Exclude:
    - bin/**/*
    - vendor/**/*
    - build/**/*
    - gemfiles/**/*

# It's a deliberate idiom in RSpec.
# See: https://github.com/bbatsov/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

# Disable regular Rails spec paths.
Rails/FilePath:
  Enabled: false

# Because we just implemented the ActiveRecord API.
Rails/SkipsModelValidations:
  Enabled: false

# We do not have a full Rails application here.
Rails/ApplicationRecord:
  Enabled: false

# We do not have a full Rails application here.
Rails/ApplicationJob:
  Enabled: false

# Because +enqueued_jobs+ is a method not a memoized variable,
# so when first evaluated it won't change.
RSpec/ExpectChange:
  Enabled: false
