sudo: false

services:
  - postgresql

language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2

gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

before_install:
  - gem install bundler
  - psql -c 'create database alarmable;' -U postgres

script: bundle exec rake
